# Generated by Django 2.2 on 2019-09-16 15:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField()),
                ('point', django.contrib.gis.db.models.fields.PointField(default=None, null=True, srid=4326)),
                ('snmp_community', models.TextField(blank=True, default='', help_text='string used to authenticate SNMP queries')),
                ('snmp_connection', models.BooleanField(default=False)),
                ('point_via_snmp', models.BooleanField(default=False, help_text='True when getting point coordinates via snmp')),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='number used to identify interface in MIB')),
                ('name', models.TextField(blank=True, default='')),
                ('speed', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('aggregate_interface', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aggregate', to='map.Interface')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('local_interface', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_interface', to='map.Interface')),
                ('remote_interface', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='map.Interface')),
            ],
        ),
    ]
