# Generated by Django 2.2 on 2020-04-06 11:12

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceMapRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(default=None, null=True, srid=4326)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('display_link_descriptions', models.BooleanField(default=True)),
                ('links_default_width', models.PositiveIntegerField(default=3, validators=[
                    django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)])),
                ('highlighted_links_width', models.PositiveIntegerField(blank=True, default=None, null=True,
                                                                        validators=[
                                                                            django.core.validators.MinValueValidator(1),
                                                                            django.core.validators.MaxValueValidator(
                                                                                15)])),
                ('highlighted_links_range_min', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('highlighted_links_range_max', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('devices', models.ManyToManyField(through='map.DeviceMapRelationship', to='data.Device')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='devicemaprelationship',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Map'),
        ),
    ]
