dist: xenial
services:
  - redis-server
addons:
  postgresql: '10'
  apt:
    packages:
      - postgresql-10-postgis-2.4
      - postgresql-10-postgis-2.4-scripts
      - postgresql-client-10
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq snmp libsnmp-dev gdal-bin
language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements/local.txt
before_script:
  - psql -c 'create database travis_db;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d travis_db
  - export DATABASE_URL='postgres://postgres@localhost:5432/travis_db'
  - export CELERY_BROKER_URL='redis://localhost:6379'
  - export REDIS_HOST='localhost'
  - export PYTHONPATH="router-map"

script:
  - python manage.py test
  - flake8
