# Generated by Django 2.2 on 2020-05-04 10:00

from django.db import migrations


def forwards_func(apps, schema_editor):
    group = apps.get_model("auth", "Group")
    permission = apps.get_model("auth", "Permission")

    visualisation_admin_group = group.objects.create(name="visualisation_admin")
    visualisation_admin_permissions = permission.objects.filter(
        codename__in=['change_map', 'add_map', 'change_diagram', 'add_diagram', 'delete_link'])
    visualisation_admin_group.permissions.set(visualisation_admin_permissions)

    account_admin_group = group.objects.create(name="account_admin")
    account_admin_permissions = permission.objects.filter(codename__in=['add_user', 'change_user', 'view_user'])
    account_admin_group.permissions.set(account_admin_permissions)


def reverse_func(apps, schema_editor):
    group = apps.get_model("auth", "Group")
    group.objects.filter(name__in=["visualisation_admin", "account_admin"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('data', '0001_initial'),
        ('map', '0001_initial'),
        ('diagram', '0001_initial'),
        ('auth', '0001_initial')
    ]
    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
