# Generated by Django 2.2 on 2020-09-25 13:44

from django.db import migrations


def forwards_func(apps, schema_editor):
    group = apps.get_model("auth", "Group")
    permission = apps.get_model("auth", "Permission")

    visualisation_admin_group = group.objects.get(name="visualisation_admin")
    new_visualisation_admin_permissions = permission.objects.filter(
        codename__in=['add_device', 'change_device', 'delete_device'])
    for perm in new_visualisation_admin_permissions:
        visualisation_admin_group.permissions.add(perm)


def reverse_func(apps, schema_editor):
    group = apps.get_model("auth", "Group")
    permission = apps.get_model("auth", "Permission")
    visualisation_admin_group = group.objects.get(name="visualisation_admin")
    permissions = permission.objects.filter(codename__in=['add_device', 'change_device', 'delete_device'])
    for perm in permissions:
        visualisation_admin_group.permissions.remove(perm)


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
