# Generated by Django 2.2 on 2020-07-06 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('visualisation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualisation',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='parent node in tree view of visualisations', null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='children',
                                    to='visualisation.Visualisation'),
        ),
    ]
